name: Deploy to EC2

on:
  push:
    paths:
      - 'Flask_backend/aws_ec2/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}  # 또는 다른 사용자 이름

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install --upgrade pip

    - name: Copy files to EC2
      run: |
        echo "${{ env.SSH_PRIVATE_KEY }}" > /tmp/ec2-key.pem
        chmod 600 /tmp/ec2-key.pem

    - name: Copy files to EC2
      run: |
        scp -i /tmp/ec2-key.pem -o StrictHostKeyChecking=no ./Flask_backend/aws_ec2/app.py ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:~/ec2
        scp -i /tmp/ec2-key.pem -o StrictHostKeyChecking=no ./Flask_backend/aws_ec2/cnn_model.py ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:~/ec2
        scp -i /tmp/ec2-key.pem -o StrictHostKeyChecking=no ./Flask_backend/aws_ec2/module_import_example.py ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:~/ec2
        scp -i /tmp/ec2-key.pem -o StrictHostKeyChecking=no ./Flask_backend/aws_ec2/personal_color.py ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:~/ec2
    
    - name: Run app.py on EC2
      run: |
        ssh -i /tmp/ec2-key.pem ${{ env.EC2_USER }}@${{ env.EC2_HOST }} "
        sudo kill -9 \$(ps -ef | grep python3 | awk '{print \$2}' | head -n -2) && \
        cd ~/ec2 && \
        nohup python3 /home/ubuntu/ec2/app.py &"
